name: Build packages

on: workflow_dispatch

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
        sdk:
          - SNAPSHOT

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0





      - name: Building packages
        uses: davidtall/gh-action-sdk@go1.24
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-daed
          NO_REFRESH_CHECK: true

      - name: Verify packages saved
        run: |
          find bin/packages/${{ matrix.arch }}/packages_ci/ -maxdepth 1 -name '*.[ai]pk' -type f | grep .
          

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.apk

      - name: Upload packages
        uses: ncipollo/release-action@main
        with:
          name: daed_${{ env.version }}
          allowUpdates: true
          tag: daed_${{ env.version }}
          replacesArtifacts: true
          artifacts: "bin/packages/${{ matrix.arch }}/packages_ci/*.apk"
